version: '3.8'

services:
  table-order-client:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - table-order-network

networks:
  table-order-network:
    driver: bridge 